services:
  gabyquiles_jwt_auth_extensions.jwk_key_loader:
    class: GabyQuiles\Auth\Loaders\JwkKeyLoader

  gabyquiles_jwt_auth_extensions.aws_jwt_provider:
    class: GabyQuiles\Auth\Providers\AwsJwsProvider
    arguments:
      $keyLoader: '@gabyquiles_jwt_auth_extensions.jwk_key_loader'
      $ttl: '%gaby_quiles_auth_jws.token_ttl%'
      $clockSkew: '%gaby_quiles_auth_jws.clock_skew%'