services:
  gaby_quiles_auth_jws.jwk_fetcher:
    class: GabyQuiles\Auth\Loaders\JwkFetcher
    arguments:
      $logger: '@logger'

  gaby_quiles_auth_jws.converter:
    class: CoderCat\JWKToPEM\JWKConverter

  gaby_quiles_auth_jws.signer_factory:
    class: GabyQuiles\Auth\Signer\SignerFactory

  gaby_quiles_auth_jws.jwk_key_loader:
    class: GabyQuiles\Auth\Loaders\JwkKeyLoader
    arguments:
      $cache: '@cache.app'
      $jwkFetcher: '@gaby_quiles_auth_jws.jwk_fetcher'
      $converter: '@gaby_quiles_auth_jws.converter'

  gaby_quiles_auth_jws.aws_jwt_provider:
    class: GabyQuiles\Auth\Providers\AwsJwsProvider
    arguments:
      $factory: '@gaby_quiles_auth_jws.signer_factory'
      $keyLoader: '@gaby_quiles_auth_jws.jwk_key_loader'
      $ttl: '%gaby_quiles_auth_jws.token_ttl%'
      $clockSkew: '%gaby_quiles_auth_jws.clock_skew%'